show_json_schema:
    path: /api/schemas/{alias}.json
    defaults: { _controller: json_schema.controller:showAction, , _format: json }

index_json_schema:
    path: /api/schemas.json
    defaults: { _controller: json_schema.controller:indexAction, _format: json }
